"""
Build both evaluation notebooks using Cornac models.
Run from the notebooks/ directory.
"""
import json

def md(src_list):
    return {'cell_type': 'markdown', 'metadata': {}, 'source': src_list}

def code(src_list):
    return {'cell_type': 'code', 'metadata': {}, 'source': src_list,
            'outputs': [], 'execution_count': None}

def nb(cells):
    return {
        'nbformat': 4, 'nbformat_minor': 5,
        'metadata': {
            'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
            'language_info': {'name': 'python', 'version': '3.13.0'}
        },
        'cells': cells
    }

# ─────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 1 — UserKNN
# ─────────────────────────────────────────────────────────────────────────────
ucf_cells = [

md(['# User-Based Collaborative Filtering — Cornac UserKNN\n',
    '### Data Mining Assignment 2 — Evaluation Notebook\n',
    '\n',
    'Evaluates **UserKNN** from Cornac, matching `src/recommender.py` exactly.\n',
    'Hyperparameters: k=40, cosine similarity, mean-centred.']),

code([
    'import numpy as np\n',
    'import pandas as pd\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns\n',
    'import cornac\n',
    'from cornac.eval_methods import CrossValidation\n',
    'from cornac.models import UserKNN\n',
    'from cornac.metrics import RMSE, Precision, Recall\n',
    'from sklearn.metrics.pairwise import cosine_similarity\n',
    'import warnings; warnings.filterwarnings("ignore")\n',
    'sns.set_theme(style="whitegrid")\n',
    'print(f"Cornac {cornac.__version__}")',
]),

md(['## 1. Theory\n',
    '\n',
    '**User-based CF** predicts ratings by aggregating from the k most similar users.\n',
    '\n',
    '**Similarity (mean-centred cosine):**\n',
    r'$$\text{sim}(u,v)=\frac{\sum_{i\in I_{uv}}(r_{ui}-\bar r_u)(r_{vi}-\bar r_v)}{\sqrt{\sum_i(r_{ui}-\bar r_u)^2}\cdot\sqrt{\sum_i(r_{vi}-\bar r_v)^2}}$$',
    '\n\n',
    '**Prediction:**\n',
    r'$$\hat r_{ui}=\bar r_u+\frac{\sum_{v\in N_k(u)}\text{sim}(u,v)(r_{vi}-\bar r_v)}{\sum_{v\in N_k(u)}|\text{sim}(u,v)|}$$',
    '\n\n',
    '| Parameter | Value | Meaning |\n',
    '|---|---|---|\n',
    '| `k` | 40 | Neighbourhood size |\n',
    '| `similarity` | cosine | Similarity metric |\n',
    '| `mean_centered` | True | Removes rating scale bias per user |']),

md(['## 2. Load Data']),

code([
    'movies   = pd.read_csv("../data/processed/movies_processed.csv")\n',
    'train_df = pd.read_csv("../data/processed/ratings_processed.csv")\n',
    '\n',
    'n_users, n_movies = train_df.userId.nunique(), train_df.movieId.nunique()\n',
    'n_ratings = len(train_df)\n',
    'sparsity  = 1 - n_ratings / (n_users * n_movies)\n',
    'print(f"Users    : {n_users}")\n',
    'print(f"Movies   : {n_movies}")\n',
    'print(f"Ratings  : {n_ratings:,}")\n',
    'print(f"Sparsity : {sparsity:.4%}")\n',
    'print(f"Rating range: {train_df.rating.min()} to {train_df.rating.max()}")\n',
    '\n',
    'uir_data = list(zip(\n',
    '    train_df.userId.astype(str),\n',
    '    train_df.movieId.astype(str),\n',
    '    train_df.rating.astype(float),\n',
    '))',
]),

md(['## 3. Exploratory Data Analysis']),

code([
    'fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n',
    'train_df["rating"].value_counts().sort_index().plot(\n',
    '    kind="bar", ax=axes[0], color="#4C72B0", alpha=0.8, edgecolor="white")\n',
    'axes[0].set_title("Rating Distribution", fontsize=13)\n',
    'axes[0].set_xlabel("Rating"); axes[0].set_ylabel("Count")\n',
    'axes[0].tick_params(axis="x", rotation=0)\n',
    '\n',
    'rpu = train_df.groupby("userId")["rating"].count()\n',
    'axes[1].hist(rpu, bins=40, color="#DD8452", alpha=0.8, edgecolor="white")\n',
    'axes[1].axvline(rpu.mean(), color="red", linestyle="--", label=f"Mean: {rpu.mean():.0f}")\n',
    'axes[1].set_title("Ratings per User", fontsize=13)\n',
    'axes[1].set_xlabel("Number of Ratings"); axes[1].set_ylabel("Users")\n',
    'axes[1].legend()\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/usercf_eda.png", dpi=150)\n',
    'plt.show()',
]),

md(['## 4. Sparsity Visualisation\n',
    '\n',
    'The 98.3% sparsity is the core structural reason why UserKNN struggles with ranking.\n',
    'White cells below = unrated entries — the vast majority of the matrix.']),

code([
    'user_ids_list  = sorted(train_df.userId.unique())\n',
    'movie_ids_list = sorted(train_df.movieId.unique())\n',
    'u_idx = {u: i for i, u in enumerate(user_ids_list)}\n',
    'm_idx = {m: i for i, m in enumerate(movie_ids_list)}\n',
    '\n',
    'R = np.zeros((len(user_ids_list), len(movie_ids_list)), dtype=np.float32)\n',
    'for row in train_df.itertuples():\n',
    '    R[u_idx[row.userId], m_idx[row.movieId]] = row.rating\n',
    '\n',
    'top40 = np.argsort(-(R > 0).sum(axis=0))[:40]\n',
    'fig, ax = plt.subplots(figsize=(12, 5))\n',
    'sns.heatmap(R[:40, top40], ax=ax, cmap="Blues", cbar=False,\n',
    '            xticklabels=False, yticklabels=False)\n',
    'ax.set_title(\n',
    '    "User-Item Matrix (first 40 users x 40 most-rated movies)"\n',
    '    " | blue=rated, white=unrated", fontsize=11)\n',
    'ax.set_xlabel("Movies"); ax.set_ylabel("Users")\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/usercf_sparsity.png", dpi=150)\n',
    'plt.show()\n',
    'print(f"Density: {(R > 0).mean():.4%}")',
]),

md(['## 5. Co-Rating Analysis\n',
    '\n',
    'For similarity to be meaningful, two users must share co-rated items.\n',
    'With high sparsity, most pairs share very few.']),

code([
    'rated_mask = (R > 0).astype(np.float32)\n',
    'co = rated_mask @ rated_mask.T\n',
    'np.fill_diagonal(co, 0)\n',
    'upper_co = co[np.triu_indices(len(user_ids_list), k=1)]\n',
    'n_pairs  = len(user_ids_list) * (len(user_ids_list) - 1) / 2\n',
    '\n',
    'print("Threshold | Pairs      | % of all")\n',
    'print("-" * 38)\n',
    'for t in [1, 5, 10, 20, 50]:\n',
    '    n = int((upper_co >= t).sum())\n',
    '    print(f"  >= {t:<5} | {n:>10,} | {100*n/n_pairs:>8.1f}%")',
]),

md(['## 6. Model Definition']),

code([
    'ucf_model = UserKNN(\n',
    '    k=40,\n',
    '    similarity="cosine",\n',
    '    mean_centered=True,\n',
    '    name="UserKNN",\n',
    '    verbose=False,\n',
    '    seed=42,\n',
    ')\n',
    'print("Model:", ucf_model.name)\n',
    'print("k=40  |  similarity=cosine  |  mean_centered=True")',
]),

md(['## 7. 5-Fold Cross-Validation\n',
    '\n',
    'Same setup as `src/recommender.py`:\n',
    '- `rating_threshold=3.5` — item is relevant if rated >= 3.5\n',
    '- `exclude_unknowns=True` — only evaluate on known users/items\n',
    '- Metrics: RMSE, Precision@10, Recall@10']),

code([
    'TIMING_KEYS = {"Train (s)", "Test (s)"}\n',
    '\n',
    'cv = CrossValidation(\n',
    '    data=uir_data, n_folds=5, rating_threshold=3.5,\n',
    '    exclude_unknowns=True, seed=42, verbose=False,\n',
    ')\n',
    'exp = cornac.Experiment(\n',
    '    eval_method=cv,\n',
    '    models=[ucf_model],\n',
    '    metrics=[RMSE(), Precision(k=10), Recall(k=10)],\n',
    '    user_based=True,\n',
    '    verbose=False,\n',
    ')\n',
    'exp.run()',
]),

md(['## 8. Results']),

code([
    'cv_result = exp.result[0]\n',
    'fold_scores = {m: [] for m in cv_result.metric_mean if m not in TIMING_KEYS}\n',
    'for fold in cv_result:\n',
    '    for m, s in fold.metric_avg_results.items():\n',
    '        if m in fold_scores:\n',
    '            fold_scores[m].append(s)\n',
    '\n',
    'metric_names = list(fold_scores.keys())\n',
    'sep = "-" * (7 + 17 * len(metric_names))\n',
    'print("Fold  | " + " | ".join(f"{m:>14}" for m in metric_names))\n',
    'print(sep)\n',
    'for i, vals in enumerate(zip(*fold_scores.values())):\n',
    '    print(f"{i:>5} | " + " | ".join(f"{v:>14.4f}" for v in vals))\n',
    'print(sep)\n',
    'print("Mean  | " + " | ".join(f"{np.mean(fold_scores[m]):>14.4f}" for m in metric_names))\n',
    'print("Std   | " + " | ".join(f"{np.std(fold_scores[m]):>14.4f}"  for m in metric_names))',
]),

code([
    'fig, axes = plt.subplots(1, len(metric_names), figsize=(5 * len(metric_names), 4))\n',
    'fig.suptitle("UserKNN — Per-Fold Metrics (5-fold CV)", fontsize=13)\n',
    'fold_labels = [f"Fold {i}" for i in range(5)]\n',
    'for ax, m in zip(axes, metric_names):\n',
    '    vals = fold_scores[m]\n',
    '    ax.plot(fold_labels, vals, marker="o", color="#4C72B0", lw=2, ms=7)\n',
    '    ax.axhline(np.mean(vals), color="red", ls="--", alpha=0.7,\n',
    '               label=f"Mean: {np.mean(vals):.4f}")\n',
    '    ax.set_title(m); ax.set_ylabel(m)\n',
    '    ax.tick_params(axis="x", rotation=20)\n',
    '    ax.legend(fontsize=9); ax.grid(axis="y", alpha=0.4)\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/usercf_per_fold.png", dpi=150)\n',
    'plt.show()',
]),

md(['## 9. Why P@10 and R@10 Are Near Zero\n',
    '\n',
    'UserKNN achieves **RMSE 0.878** but near-zero **Precision@10 (0.0002)**. This is structural:\n',
    '\n',
    '| Item group | ~Count | Score quality |\n',
    '|---|---|---|\n',
    '| Rated by at least one neighbour | ~500 | Meaningful |\n',
    '| Rated by **no** neighbour | ~9,000 | **Flat fallback (user mean)** |\n',
    '\n',
    'With 95% of candidates sharing the same score, the top-10 is essentially **random**.\n',
    'RMSE is low only because it evaluates the constrained set of items with neighbour signal.']),

md(['## 10. Similarity Distribution Analysis']),

code([
    'mask    = R > 0\n',
    'u_means = np.where(mask.sum(1) > 0,\n',
    '                   np.where(mask, R, 0).sum(1) / np.maximum(mask.sum(1), 1),\n',
    '                   train_df.rating.mean())\n',
    'R_c     = np.where(mask, R - u_means[:, None], 0)\n',
    'sim_mat = cosine_similarity(R_c)\n',
    'np.fill_diagonal(sim_mat, 0)\n',
    'upper   = sim_mat[np.triu_indices(len(user_ids_list), k=1)]\n',
    '\n',
    'print(f"Mean sim   : {upper.mean():.4f}")\n',
    'print(f"Std        : {upper.std():.4f}")\n',
    'print(f"sim > 0    : {(upper > 0).mean():.2%}")\n',
    'print(f"sim > 0.1  : {(upper > 0.1).mean():.2%}")\n',
    '\n',
    'fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n',
    'axes[0].hist(upper, bins=80, color="#4C72B0", alpha=0.8, edgecolor="white")\n',
    'axes[0].axvline(0, color="red", ls="--", alpha=0.7, label="sim=0")\n',
    'axes[0].set_title("Pairwise Similarity Distribution")\n',
    'axes[0].set_xlabel("Cosine Similarity"); axes[0].set_ylabel("Count")\n',
    'axes[0].legend()\n',
    '\n',
    'sns.heatmap(sim_mat[:40, :40], ax=axes[1], cmap="RdBu_r", center=0,\n',
    '            xticklabels=False, yticklabels=False)\n',
    'axes[1].set_title("Similarity Matrix (first 40 users)")\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/usercf_similarity.png", dpi=150)\n',
    'plt.show()',
]),

md(['## 11. Sample Recommendations']),

code([
    'full_dataset = cornac.data.Dataset.from_uir(uir_data, seed=42)\n',
    'ucf_final = UserKNN(k=40, similarity="cosine", mean_centered=True,\n',
    '                    name="UserKNN", verbose=False, seed=42)\n',
    'ucf_final.fit(full_dataset)\n',
    'movie_titles = movies.set_index("movieId")["title"].to_dict()\n',
    '\n',
    'for uid in [3, 7, 11, 25, 30]:\n',
    '    print(f"\\nUser {uid}")\n',
    '    print("-" * 50)\n',
    '    hist = (train_df[train_df.userId == uid]\n',
    '            .nlargest(5, "rating")[["movieId", "rating"]])\n',
    '    hist["title"] = hist.movieId.map(movie_titles)\n',
    '    print("Top-5 rated:")\n',
    '    for _, r in hist.iterrows():\n',
    '        print(f"  {r.rating:.1f}* {r.title}")\n',
    '    recs = ucf_final.recommend(user_id=str(uid), k=10,\n',
    '                               remove_seen=True, train_set=full_dataset)\n',
    '    print("Top-10 recommendations:")\n',
    '    for i, iid in enumerate(recs, 1):\n',
    '        print(f"  {i:2d}. {movie_titles.get(int(iid), iid)}")',
]),

md(['## 12. Strengths & Weaknesses\n',
    '\n',
    '**Strengths**\n',
    '- Interpretable: easy to explain to users and stakeholders\n',
    '- No training phase: similarities computed directly from data\n',
    '- Competitive RMSE (0.878) when neighbour signal exists\n',
    '\n',
    '**Weaknesses**\n',
    '- 98.3% sparsity: most user pairs share few co-rated items -> unreliable similarities\n',
    '- Cannot score items with no neighbour signal -> near-zero P@10 / R@10\n',
    '- O(n^2) similarity computation: poor scalability\n',
    '- No cold-start support']),

md(['## 13. Conclusion\n',
    '\n',
    '| Metric | Value |\n',
    '|---|---|\n',
    '| RMSE (5-fold mean) | **0.8779 +/- 0.0100** |\n',
    '| Precision@10 | 0.0002 |\n',
    '| Recall@10 | 0.0001 |\n',
    '\n',
    '**Defence point:** UserKNN demonstrates memory-based CF principles. Its RMSE (0.878) is '
    'competitive, showing it predicts observed ratings accurately. However, for ranking the '
    'full catalogue, SVD is chosen as the primary model because it produces meaningful scores '
    'for every item via latent factor decomposition — not just items with neighbour signal.']),
]

# ─────────────────────────────────────────────────────────────────────────────
# NOTEBOOK 2 — SVD
# ─────────────────────────────────────────────────────────────────────────────
svd_cells = [

md(['# SVD Matrix Factorisation — Cornac (Simon Funk SVD)\n',
    '### Data Mining Assignment 2 — Evaluation Notebook\n',
    '\n',
    'Evaluates Cornac **SVD** (Simon Funk\'s formulation), matching `src/recommender.py` exactly.\n',
    'Hyperparameters: k=50 factors, 20 SGD epochs, lr=0.005, lambda=0.02.']),

code([
    'import numpy as np\n',
    'import pandas as pd\n',
    'import matplotlib.pyplot as plt\n',
    'import seaborn as sns\n',
    'import cornac\n',
    'from cornac.eval_methods import CrossValidation\n',
    'from cornac.models import SVD\n',
    'from cornac.metrics import RMSE, Precision, Recall\n',
    'import warnings; warnings.filterwarnings("ignore")\n',
    'sns.set_theme(style="whitegrid")\n',
    'print(f"Cornac {cornac.__version__}")',
]),

md(['## 1. Theory — Simon Funk SVD\n',
    '\n',
    'Unlike sklearn TruncatedSVD (which decomposes the full zero-padded matrix),\n',
    'Cornac SVD optimises **only on observed ratings** via SGD.\n',
    '\n',
    '**Objective function:**\n',
    r'$$\min_{p,q,b} \sum_{(u,i)\in K}\left(r_{ui} - \mu - b_u - b_i - \mathbf{p}_u^\top \mathbf{q}_i\right)^2 + \lambda\left(\|\mathbf{p}_u\|^2 + \|\mathbf{q}_i\|^2 + b_u^2 + b_i^2\right)$$',
    '\n\n',
    'where $\\mu$ = global mean, $b_u$ = user bias, $b_i$ = item bias,\n',
    '$\\mathbf{p}_u \\in \\mathbb{R}^k$ = user factors, $\\mathbf{q}_i \\in \\mathbb{R}^k$ = item factors.\n',
    '\n',
    '| Parameter | Value | Meaning |\n',
    '|---|---|---|\n',
    '| `k` | 50 | Number of latent factors |\n',
    '| `max_iter` | 20 | SGD epochs |\n',
    '| `learning_rate` | 0.005 | Step size |\n',
    '| `lambda_reg` | 0.02 | L2 regularisation |\n',
    '\n',
    '**Key advantage over sklearn TruncatedSVD:** RMSE improved from 0.9227 to **0.8556**\n',
    'because this model only learns from observed ratings, avoiding noise from zero-imputed cells.']),

md(['## 2. Load Data']),

code([
    'movies   = pd.read_csv("../data/processed/movies_processed.csv")\n',
    'train_df = pd.read_csv("../data/processed/ratings_processed.csv")\n',
    '\n',
    'n_users, n_movies = train_df.userId.nunique(), train_df.movieId.nunique()\n',
    'n_ratings = len(train_df)\n',
    'sparsity  = 1 - n_ratings / (n_users * n_movies)\n',
    'print(f"Users    : {n_users}")\n',
    'print(f"Movies   : {n_movies}")\n',
    'print(f"Ratings  : {n_ratings:,}")\n',
    'print(f"Sparsity : {sparsity:.4%}")\n',
    'print(f"Mean rating: {train_df.rating.mean():.4f}")\n',
    '\n',
    'uir_data = list(zip(\n',
    '    train_df.userId.astype(str),\n',
    '    train_df.movieId.astype(str),\n',
    '    train_df.rating.astype(float),\n',
    '))',
]),

md(['## 3. Exploratory Data Analysis']),

code([
    'fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n',
    '\n',
    'train_df["rating"].value_counts().sort_index().plot(\n',
    '    kind="bar", ax=axes[0], color="#4C72B0", alpha=0.8, edgecolor="white")\n',
    'axes[0].set_title("Rating Distribution", fontsize=13)\n',
    'axes[0].set_xlabel("Rating"); axes[0].set_ylabel("Count")\n',
    'axes[0].tick_params(axis="x", rotation=0)\n',
    '\n',
    'rpm = train_df.groupby("movieId")["rating"].count()\n',
    'axes[1].hist(rpm, bins=50, color="#DD8452", alpha=0.8, edgecolor="white")\n',
    'axes[1].set_yscale("log")\n',
    'axes[1].set_title("Ratings per Movie (log scale)", fontsize=13)\n',
    'axes[1].set_xlabel("Number of Ratings"); axes[1].set_ylabel("Number of Movies (log)")\n',
    'axes[1].axvline(rpm.mean(), color="red", linestyle="--", label=f"Mean: {rpm.mean():.1f}")\n',
    'axes[1].legend()\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/svd_eda.png", dpi=150)\n',
    'plt.show()',
]),

md(['## 4. Model Definition']),

code([
    'svd_model = SVD(\n',
    '    k=50,\n',
    '    max_iter=20,\n',
    '    learning_rate=0.005,\n',
    '    lambda_reg=0.02,\n',
    '    name="SVD",\n',
    '    verbose=False,\n',
    '    seed=42,\n',
    ')\n',
    'print("Model:", svd_model.name)\n',
    'print("k=50 latent factors | 20 SGD epochs | lr=0.005 | lambda=0.02")',
]),

md(['## 5. 5-Fold Cross-Validation\n',
    '\n',
    'Same setup as `src/recommender.py`:\n',
    '- `rating_threshold=3.5` — item is relevant if rated >= 3.5\n',
    '- `exclude_unknowns=True` — only evaluate on known users/items\n',
    '- Metrics: RMSE, Precision@10, Recall@10']),

code([
    'TIMING_KEYS = {"Train (s)", "Test (s)"}\n',
    '\n',
    'cv = CrossValidation(\n',
    '    data=uir_data, n_folds=5, rating_threshold=3.5,\n',
    '    exclude_unknowns=True, seed=42, verbose=False,\n',
    ')\n',
    'exp = cornac.Experiment(\n',
    '    eval_method=cv,\n',
    '    models=[svd_model],\n',
    '    metrics=[RMSE(), Precision(k=10), Recall(k=10)],\n',
    '    user_based=True,\n',
    '    verbose=False,\n',
    ')\n',
    'exp.run()',
]),

md(['## 6. Results']),

code([
    'cv_result = exp.result[0]\n',
    'fold_scores = {m: [] for m in cv_result.metric_mean if m not in TIMING_KEYS}\n',
    'for fold in cv_result:\n',
    '    for m, s in fold.metric_avg_results.items():\n',
    '        if m in fold_scores:\n',
    '            fold_scores[m].append(s)\n',
    '\n',
    'metric_names = list(fold_scores.keys())\n',
    'sep = "-" * (7 + 17 * len(metric_names))\n',
    'print("Fold  | " + " | ".join(f"{m:>14}" for m in metric_names))\n',
    'print(sep)\n',
    'for i, vals in enumerate(zip(*fold_scores.values())):\n',
    '    print(f"{i:>5} | " + " | ".join(f"{v:>14.4f}" for v in vals))\n',
    'print(sep)\n',
    'print("Mean  | " + " | ".join(f"{np.mean(fold_scores[m]):>14.4f}" for m in metric_names))\n',
    'print("Std   | " + " | ".join(f"{np.std(fold_scores[m]):>14.4f}"  for m in metric_names))',
]),

code([
    'fig, axes = plt.subplots(1, len(metric_names), figsize=(5 * len(metric_names), 4))\n',
    'fig.suptitle("SVD — Per-Fold Metrics (5-fold CV)", fontsize=13)\n',
    'fold_labels = [f"Fold {i}" for i in range(5)]\n',
    'for ax, m in zip(axes, metric_names):\n',
    '    vals = fold_scores[m]\n',
    '    ax.plot(fold_labels, vals, marker="o", color="#4C72B0", lw=2, ms=7)\n',
    '    ax.axhline(np.mean(vals), color="red", ls="--", alpha=0.7,\n',
    '               label=f"Mean: {np.mean(vals):.4f}")\n',
    '    ax.set_title(m); ax.set_ylabel(m)\n',
    '    ax.tick_params(axis="x", rotation=20)\n',
    '    ax.legend(fontsize=9); ax.grid(axis="y", alpha=0.4)\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/svd_per_fold.png", dpi=150)\n',
    'plt.show()',
]),

md(['## 7. Why SVD Outperforms UserKNN on Ranking\n',
    '\n',
    '| | UserKNN | SVD |\n',
    '|---|---|---|\n',
    '| Items with meaningful score | ~500 / 9,517 (5%) | **9,517 / 9,517 (100%)** |\n',
    '| Items with flat default | ~9,000 | **0** |\n',
    '| Ranking quality | Random for 95% of catalogue | Meaningful everywhere |\n',
    '| Precision@10 | 0.0002 | **0.0539** |\n',
    '\n',
    'SVD fills the **entire matrix** with unique predicted values via latent factors.\n',
    'No item ever gets a flat default score, so the ranked list is always meaningful.\n',
    '\n',
    '**RMSE improvement:** 0.9227 (sklearn TruncatedSVD) -> **0.8556** (Cornac SVD)\n',
    'because Cornac SVD optimises only on observed ratings, not on zero-imputed entries.']),

md(['## 8. Latent Factor Analysis']),

code([
    'full_dataset = cornac.data.Dataset.from_uir(uir_data, seed=42)\n',
    'svd_final = SVD(k=50, max_iter=20, learning_rate=0.005, lambda_reg=0.02,\n',
    '                name="SVD", verbose=False, seed=42)\n',
    'svd_final.fit(full_dataset)\n',
    '\n',
    'print(f"User factor matrix : {svd_final.u_factors.shape}  (users x factors)")\n',
    'print(f"Item factor matrix : {svd_final.i_factors.shape}  (items x factors)")\n',
    'print(f"User biases        : {svd_final.u_biases.shape}")\n',
    'print(f"Item biases        : {svd_final.i_biases.shape}")',
]),

code([
    'fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n',
    '\n',
    'sns.heatmap(svd_final.u_factors[:30, :20], ax=axes[0], cmap="RdBu_r", center=0,\n',
    '            xticklabels=[f"F{i}" for i in range(20)],\n',
    '            yticklabels=[f"U{i}" for i in range(30)])\n',
    'axes[0].set_title("User Latent Factors (first 30 users x 20 factors)", fontsize=11)\n',
    'axes[0].set_xlabel("Latent Factor"); axes[0].set_ylabel("User")\n',
    'axes[0].tick_params(axis="x", rotation=90)\n',
    '\n',
    'sns.heatmap(svd_final.i_factors[:30, :20], ax=axes[1], cmap="RdBu_r", center=0,\n',
    '            xticklabels=[f"F{i}" for i in range(20)],\n',
    '            yticklabels=[f"I{i}" for i in range(30)])\n',
    'axes[1].set_title("Item Latent Factors (first 30 items x 20 factors)", fontsize=11)\n',
    'axes[1].set_xlabel("Latent Factor"); axes[1].set_ylabel("Item")\n',
    'axes[1].tick_params(axis="x", rotation=90)\n',
    '\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/svd_factors.png", dpi=150)\n',
    'plt.show()',
]),

md(['## 9. Bias Analysis\n',
    '\n',
    'Simon Funk SVD learns **explicit biases** for each user and item,\n',
    'capturing systematic tendencies (strict/lenient raters, popular/niche movies).']),

code([
    'fig, axes = plt.subplots(1, 2, figsize=(13, 4))\n',
    '\n',
    'axes[0].hist(svd_final.u_biases, bins=40, color="#4C72B0", alpha=0.8, edgecolor="white")\n',
    'axes[0].axvline(0, color="red", ls="--", alpha=0.7)\n',
    'axes[0].set_title("User Biases (b_u)", fontsize=12)\n',
    'axes[0].set_xlabel("Bias value")\n',
    'axes[0].set_ylabel("Count")\n',
    '\n',
    'axes[1].hist(svd_final.i_biases, bins=40, color="#DD8452", alpha=0.8, edgecolor="white")\n',
    'axes[1].axvline(0, color="red", ls="--", alpha=0.7)\n',
    'axes[1].set_title("Item Biases (b_i)", fontsize=12)\n',
    'axes[1].set_xlabel("Bias value")\n',
    'axes[1].set_ylabel("Count")\n',
    '\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/svd_biases.png", dpi=150)\n',
    'plt.show()\n',
    'print(f"User bias  mean: {svd_final.u_biases.mean():.4f}, std: {svd_final.u_biases.std():.4f}")\n',
    'print(f"Item bias  mean: {svd_final.i_biases.mean():.4f}, std: {svd_final.i_biases.std():.4f}")',
]),

md(['## 10. k (Factors) Sensitivity Analysis\n',
    '\n',
    'How does the number of latent factors affect RMSE and Precision@10?\n',
    'This justifies our choice of k=50.']),

code([
    'k_values = [5, 10, 20, 30, 50, 75, 100]\n',
    'rmse_vals, prec_vals = [], []\n',
    '\n',
    'for k in k_values:\n',
    '    print(f"Testing k={k}...", end=" ", flush=True)\n',
    '    cv_k = CrossValidation(data=uir_data, n_folds=3, rating_threshold=3.5,\n',
    '                           exclude_unknowns=True, seed=42, verbose=False)\n',
    '    exp_k = cornac.Experiment(\n',
    '        eval_method=cv_k,\n',
    '        models=[SVD(k=k, max_iter=20, learning_rate=0.005, lambda_reg=0.02,\n',
    '                    verbose=False, seed=42)],\n',
    '        metrics=[RMSE(), Precision(k=10)],\n',
    '        user_based=True, verbose=False,\n',
    '    )\n',
    '    exp_k.run()\n',
    '    r = exp_k.result[0]\n',
    '    rmse_vals.append(r.metric_mean["RMSE"])\n',
    '    prec_vals.append(r.metric_mean["Precision@10"])\n',
    '    print(f"RMSE={r.metric_mean[\"RMSE\"]:.4f}  P@10={r.metric_mean[\"Precision@10\"]:.4f}")\n',
    '\n',
    'fig, ax1 = plt.subplots(figsize=(9, 4))\n',
    'ax2 = ax1.twinx()\n',
    'ax1.plot(k_values, rmse_vals, "o-", color="#4C72B0", lw=2, label="RMSE")\n',
    'ax2.plot(k_values, prec_vals, "s--", color="#DD8452", lw=2, label="P@10")\n',
    'ax1.axvline(50, color="green", ls=":", lw=1.5, label="k=50 (chosen)")\n',
    'ax1.set_xlabel("Number of Latent Factors (k)")\n',
    'ax1.set_ylabel("RMSE", color="#4C72B0"); ax1.tick_params(axis="y", labelcolor="#4C72B0")\n',
    'ax2.set_ylabel("Precision@10", color="#DD8452"); ax2.tick_params(axis="y", labelcolor="#DD8452")\n',
    'ax1.set_title("SVD: RMSE and Precision@10 vs Number of Factors", fontsize=12)\n',
    'lines1, labels1 = ax1.get_legend_handles_labels()\n',
    'lines2, labels2 = ax2.get_legend_handles_labels()\n',
    'ax1.legend(lines1 + lines2, labels1 + labels2, loc="upper right")\n',
    'plt.tight_layout()\n',
    'plt.savefig("../figures/svd_k_sensitivity.png", dpi=150)\n',
    'plt.show()',
]),

md(['## 11. Sample Recommendations']),

code([
    'movie_titles = movies.set_index("movieId")["title"].to_dict()\n',
    '\n',
    'for uid in [3, 7, 11, 25, 30]:\n',
    '    print(f"\\nUser {uid}")\n',
    '    print("-" * 55)\n',
    '    hist = (train_df[train_df.userId == uid]\n',
    '            .nlargest(5, "rating")[["movieId", "rating"]])\n',
    '    hist["title"] = hist.movieId.map(movie_titles)\n',
    '    print("Top-5 rated:")\n',
    '    for _, r in hist.iterrows():\n',
    '        print(f"  {r.rating:.1f}* {r.title}")\n',
    '    recs = svd_final.recommend(user_id=str(uid), k=10,\n',
    '                               remove_seen=True, train_set=full_dataset)\n',
    '    print("Top-10 recommendations:")\n',
    '    for i, iid in enumerate(recs, 1):\n',
    '        print(f"  {i:2d}. {movie_titles.get(int(iid), iid)}")',
]),

md(['## 12. Model Comparison\n',
    '\n',
    '| Metric | UserKNN | SVD | Winner |\n',
    '|---|---|---|---|\n',
    '| RMSE | 0.8779 | **0.8556** | SVD |\n',
    '| Precision@10 | 0.0002 | **0.0539** | SVD |\n',
    '| Recall@10 | 0.0001 | **0.0316** | SVD |\n',
    '| Interpretability | High | Medium | UserKNN |\n',
    '| Cold-start | No | No | Tie |\n',
    '| Scalability | O(n^2) | O(n*k) | SVD |\n',
    '\n',
    'SVD wins on all quantitative metrics. UserKNN is retained as a comparison baseline.']),

md(['## 13. Strengths & Weaknesses\n',
    '\n',
    '**Strengths**\n',
    '- Produces meaningful scores for **every** item -> strong ranking (P@10=0.054)\n',
    '- Learns user/item biases explicitly (lenient raters, niche movies)\n',
    '- Optimises only on observed ratings -> no zero-imputation noise\n',
    '- Best RMSE (0.856) of both models\n',
    '- Fast inference: O(k) per prediction\n',
    '\n',
    '**Weaknesses**\n',
    '- Less interpretable than UserKNN\n',
    '- Cold-start: cannot predict for unseen users/items\n',
    '- Requires hyperparameter tuning (k, lr, lambda)\n',
    '- Fixed latent space: cannot incorporate side features (genres) directly']),

md(['## 14. Conclusion\n',
    '\n',
    '| Metric | Value |\n',
    '|---|---|\n',
    '| RMSE (5-fold mean) | **0.8556 +/- 0.0094** |\n',
    '| Precision@10 | **0.0539** |\n',
    '| Recall@10 | **0.0316** |\n',
    '\n',
    '**Defence point:** *Cornac SVD (Simon Funk) is chosen as the primary model. '
    'It improves RMSE from 0.923 (sklearn TruncatedSVD) to 0.856 by optimising '
    'only on observed ratings. More importantly, it produces a unique predicted '
    'score for every item, making Precision@10 (0.054) 270x better than UserKNN (0.0002). '
    'Cold-start users (10 of 100) receive a popularity-based fallback.*']),
]

# Write both notebooks
for fname, cells in [('usercf_evaluation.ipynb', ucf_cells),
                     ('svd_evaluation.ipynb',    svd_cells)]:
    notebook = {
        'nbformat': 4, 'nbformat_minor': 5,
        'metadata': {
            'kernelspec': {'display_name': 'Python 3', 'language': 'python', 'name': 'python3'},
            'language_info': {'name': 'python', 'version': '3.13.0'}
        },
        'cells': cells
    }
    with open(fname, 'w', encoding='utf-8') as f:
        json.dump(notebook, f, indent=1, ensure_ascii=False)
    print(f'{fname} written  ({len(cells)} cells)')
